/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Interface_CONSTANTS_H
#define Interface_CONSTANTS_H

#include "Interface_types.h"

namespace ThriftModule {

class InterfaceConstants {
 public:
  InterfaceConstants();

};

extern const InterfaceConstants g_Interface_constants;

} // namespace

#endif
